# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'ONNX'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: conda install -y -c conda-forge protobuf=3.5.2 numpy
    displayName: 'Install conda libraries'

  - script: |
      pip install pytest-cov nbval
    displayName: 'Install pytest'

  - task: BatchScript@1
    inputs:
      filename: .azure-pipelines/install.bat
      workingFolder: "$(Build.SourcesDirectory)"

  - task: BatchScript@1
    inputs:
      filename: .azure-pipelines/test.bat
      workingFolder: "$(Build.SourcesDirectory)"
    
